# Generated by Django 6.0.3 on 2026-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color_tag',
            field=models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('pink', 'Pink'), ('green', 'Green'), ('orange', 'Orange')], default='blue', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
