# Generated by Django 6.0.3 on 2026-03-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
